// LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// USER LOADING
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";

// CLEAR ERROR
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";

// CLEAR ERROR
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// POST WRITE
export const POSTS_WRITE_REQUEST = "POST_WRITE_REQUEST";
export const POSTS_WRITE_FAILURE = "POST_WRITE_FAILURE";
export const POSTS_WRITE_SUCCESS = "POST_WRITE_SUCCESS";

// POST WRITE
export const POSTS_LOADING_REQUEST = "POST_LOADING_REQUEST";
export const POSTS_LOADING_FAILURE = "POST_LOADING_FAILURE";
export const POSTS_LOADING_SUCCESS = "POST_LOADING_SUCCESS";

// POST UPLOAD
export const POST_UPLOADING_REQUEST = "POST_UPLOADING_REQUEST";
export const POST_UPLOADING_FAILURE = "POST_UPLOADING_FAILURE";
export const POST_UPLOADING_SUCCESS = "POST_UPLOADING_SUCCESS";

// POST Detail loading
export const POST_DETAIL_LOADING_REQUEST = "POST_DETAIL_LOADING_REQUEST";
export const POST_DETAIL_LOADING_FAILURE = "POST_DETAIL_LOADING_FAILURE";
export const POST_DETAIL_LOADING_SUCCESS = "POST_DETAIL_LOADING_SUCCESS";
// POST DELETE
export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";

// Comment loading
export const COMMENT_LOADING_REQUEST = "COMMENT_LOADING_REQUEST";
export const COMMENT_LOADING_FAILURE = "COMMENT_LOADING_FAILURE";
export const COMMENT_LOADING_SUCCESS = "COMMENT_LOADING_SUCCESS";

// Comment uploading
export const COMMENT_UPLOADING_REQUEST = "COMMENT_UPLOADING_REQUEST";
export const COMMENT_UPLOADING_FAILURE = "COMMENT_UPLOADING_FAILURE";
export const COMMENT_UPLOADING_SUCCESS = "COMMENT_UPLOADING_SUCCESS";

// Post Loading Edit
export const POST_EDIT_LOADING_REQUEST = "POST_EDIT_LOADING_REQUEST";
export const POST_EDIT_LOADING_FAILURE = "POST_EDIT_LOADING_FAILURE";
export const POST_EDIT_LOADING_SUCCESS = "POST_EDIT_LOADING_SUCCESS";

// Post Uploading Edit
export const POST_EDIT_UPLOADING_REQUEST = "POST_EDIT_UPLOADING_REQUEST";
export const POST_EDIT_UPLOADING_FAILURE = "POST_EDIT_UPLOADING_FAILURE";
export const POST_EDIT_UPLOADING_SUCCESS = "POST_EDIT_UPLOADING_SUCCESS";

// Post Uploading Edit
export const CATEGORY_FIND_REQUEST = "CATEGORY_FIND_REQUEST";
export const CATEGORY_FIND_FAILURE = "CATEGORY_FIND_FAILURE";
export const CATEGORY_FIND_SUCCESS = "CATEGORY_FIND_SUCCESS";

// Post Uploading Edit
export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";

// Password Edit
export const PASSWORD_EDIT_UPLOADING_REQUEST =
  "PASSWORD_EDIT_UPLOADING_REQUEST";
export const PASSWORD_EDIT_UPLOADING_FAILURE =
  "PASSWORD_EDIT_UPLOADING_FAILURE";
export const PASSWORD_EDIT_UPLOADING_SUCCESS =
  "PASSWORD_EDIT_UPLOADING_SUCCESS";
